#cloud-config

apt_sources:
    - source: "ppa:fenics-packages/fenics"

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - fenics
    - gmsh
    - python-numpy
    - python-matplotlib
    - python-swiftclient

runcmd:
    - pip install celery
    #- pip install python-swiftclient
    #- git clone https://github.com/vallemagnusson/naca_airfoil.git
    #- mv naca_airfoil home/ubuntu/naca_airfoil
    - export C_FORCE_ROOT="true"
    - export BROKER_USER=mava
    - export BROKER_PASS=orkarinte
    - export FLOATING_IP=130.238.29.6
    - git clone https://github.com/vallemagnusson/molnProject.git
    - mv molnProject /home/ubuntu/molnProject
    - chmod -R 777 /home/ubuntu/molnProject
    - mkdir /home/ubuntu/molnProject/msh
    - mkdir /home/ubuntu/molnProject/geo
    - chmod -R 777 /home/ubuntu/molnProject/msh/
    - chmod -R 777 /home/ubuntu/molnProject/geo/
    - export OS_AUTH_URL=http://smog.uppmax.uu.se:5000/v2.0
    - export OS_TENANT_ID=3c9d997982e04c6db0e02b82fa18fdd8
    - export OS_TENANT_NAME="ACC-Course"
    - export OS_PROJECT_NAME="ACC-Course"
    - export OS_USERNAME="mava5911"
    - export OS_PASSWORD="x1xv6565"
    - export OS_REGION_NAME="regionOne"

    #- git clone --depth 1 -b valle https://github.com/jantus/ACC-project.git
    #- mv ACC-project/naca_airfoil home/ubuntu/naca_airfoil
    #- chmod -R 777 /home/ubuntu/messaging
    #- chmod -R 777 /home/ubuntu/naca_airfoil
    #- mkdir /home/ubuntu/naca_airfoil/msh
    #- chmod -R 777 /home/ubuntu/naca_airfoil/msh/
    #- mkdir /home/ubuntu/naca_airfoil/geo
    #- chmod -R 777 /home/ubuntu/naca_airfoil/geo/
    #- cd /home/ubuntu/naca_airfoil
    - cd /home/ubuntu/molnProject
    #- chown -R ubuntu /home/ubuntu/naca_airfoil
    - celery worker -A proj &
    #- sudo -H -u ubuntu bash -c "celery worker -A proj &"
